plugins {
    id 'org.springframework.boot' version '3.1.5'
    id 'io.spring.dependency-management' version '1.1.3'
    id 'groovy'
}

group = 'de.c7h12'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Groovy
    implementation 'org.apache.groovy:groovy'

    // JSON Processing
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Utilities
    implementation 'commons-codec:commons-codec:1.15'

    // QR Code Processing
    implementation 'com.google.zxing:core:3.5.2'
    implementation 'com.google.zxing:javase:3.5.2'

    // API Documentation
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

    // Rate Limiting
    implementation 'com.github.vladimir-bukhtoyarov:bucket4j-core:7.6.0'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}